name: Chat Docker Build And Push

on:
  workflow_run:
    workflows: [Chat Service Build]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login To DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build And Push
        uses: docker/build-push-action@v4
        with:
          context: ./src/chat-service
          file: ./src/chat-service/Dockerfile
          push: true
          tags: maplefighters/chat-service:latest
