name: DigitalOcean Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_KEY }}
          port: ${{ secrets.DIGITALOCEAN_PORT }}
          script: |
            # Set File Variables
            HOST=https://raw.githubusercontent.com
            USER=codingben
            REPO_NAME=maple-fighters
            BRANCH=develop
            FILE=docker-compose.prod.yml

            # Download File
            rm ${FILE}
            curl -s ${HOST}/${USER}/${REPO_NAME}/${BRANCH}/${FILE} -o ${FILE}

            # Set Database Variables
            export AUTH_DB_USER=${{ secrets.AUTH_DB_USER }}
            export AUTH_DB_PASSWORD=${{ secrets.AUTH_DB_PASSWORD }}
            export AUTH_DB_NAME=${{ secrets.AUTH_DB_NAME }}

            export CHARACTER_DB_USER=${{ secrets.CHARACTER_DB_USER }}
            export CHARACTER_DB_PASSWORD=${{ secrets.CHARACTER_DB_PASSWORD }}
            export CHARACTER_DB_NAME=${{ secrets.CHARACTER_DB_NAME }}
            
            # Pull, Up and Clean
            docker-compose -f ${FILE} pull
            docker-compose -f ${FILE} up -d
            docker system prune -af
