name: Game Docker Build And Push

on:
  workflow_dispatch:
    # Left blank intentionally

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login To DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build And Push
        uses: docker/build-push-action@v4
        with:
          context: ./src/game-service/Game.Application
          file: ./src/game-service/Game.Application/Dockerfile
          push: true
          tags: maplefighters/game-service:1.0.0
          platforms: linux/amd64,linux/arm64/v8
